export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST"
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCES"
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR"

//users
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGIN_LOGOUT = "USER_LOGIN_LOGOUT"

//reviews
export const FETCH_REVIEWS_REQUEST = "FETCH_REVIEWS_REQUEST"
export const FETCH_REVIEWS_SUCCESS = "FETCH_REVIEWS_SUCCES"
export const FETCH_REVIEWS_ERROR = "FETCH_REVIEWS_ERROR"

//cart
export const FETCH_ITEMS_REQUEST = "FETCH_ITEMS_REQUEST"
export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const FETCH_ITEM_ERROR = "FETCH_ITEM_ERROR"

//order
export const FETCH_ORDER_CHECK_REQUEST = "FETCH_ORDER_CHECK_REQUEST"
export const FETCH_ORDER_CHECK_SUCCESS = "FETCH_ORDER_CHECK_SUCCESS"
export const FETCH_ORDER_ERROR = "FETCH_ORDER_ERROR"




